-- MySQL Script generated by MySQL Workbench
-- Mon Feb 17 12:59:28 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`carrier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carrier` (
  `id_carrier` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  PRIMARY KEY (`id_carrier`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`place` (
  `id_place` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `timezone` VARCHAR(45) NULL,
  `airport_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_place`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`connexion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`connexion` (
  `to_place_id_place` INT NOT NULL,
  `from_place_id_place` INT NOT NULL,
  `id_connexion` VARCHAR(45) NOT NULL,
  `carrier_id_carrier` INT NOT NULL AUTO_INCREMENT,
  `time` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_connexion`, `carrier_id_carrier`),
  INDEX `fk_connexion_carrier_idx` (`carrier_id_carrier` ASC) VISIBLE,
  INDEX `fk_connexion_place1_idx` (`to_place_id_place` ASC) VISIBLE,
  INDEX `fk_connexion_place2_idx` (`from_place_id_place` ASC) VISIBLE,
  CONSTRAINT `fk_connexion_carrier`
    FOREIGN KEY (`carrier_id_carrier`)
    REFERENCES `mydb`.`carrier` (`id_carrier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_connexion_place1`
    FOREIGN KEY (`to_place_id_place`)
    REFERENCES `mydb`.`place` (`id_place`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_connexion_place2`
    FOREIGN KEY (`from_place_id_place`)
    REFERENCES `mydb`.`place` (`id_place`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`flight` (
  `connexion_id_connexion` VARCHAR(45) NOT NULL,
  `connexion_carrier_id_carrier` INT NOT NULL,
  `f_date` DATE NOT NULL,
  `price` VARCHAR(45) NULL,
  `currency` VARCHAR(45) NULL,
  `seats_max` VARCHAR(45) NULL,
  `seats_ccc` VARCHAR(45) NULL,
  PRIMARY KEY (`connexion_id_connexion`, `connexion_carrier_id_carrier`, `f_date`),
  INDEX `fk_flight_connexion1_idx` (`connexion_id_connexion` ASC, `connexion_carrier_id_carrier` ASC) VISIBLE,
  INDEX `currency` (`currency` ASC) VISIBLE,
  CONSTRAINT `fk_flight_connexion1`
    FOREIGN KEY (`connexion_id_connexion` , `connexion_carrier_id_carrier`)
    REFERENCES `mydb`.`connexion` (`id_connexion` , `carrier_id_carrier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `id_customer` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `other_data` VARCHAR(45) NULL,
  PRIMARY KEY (`id_customer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`book` (
  `flight_connexion_id_connexion` VARCHAR(45) NOT NULL,
  `flight_connexion_carrier_id_carrier` INT NOT NULL,
  `flight_f_date` DATE NOT NULL,
  `id_book` INT NOT NULL,
  `customer_id_customer` INT NOT NULL,
  PRIMARY KEY (`flight_connexion_id_connexion`, `flight_connexion_carrier_id_carrier`, `flight_f_date`, `id_book`),
  INDEX `fk_book_flight1_idx` (`flight_connexion_id_connexion` ASC, `flight_connexion_carrier_id_carrier` ASC, `flight_f_date` ASC) INVISIBLE,
  INDEX `fk_book_customer1_idx` (`customer_id_customer` ASC) VISIBLE,
  INDEX () VISIBLE,
  CONSTRAINT `fk_book_flight1`
    FOREIGN KEY (`flight_connexion_id_connexion` , `flight_connexion_carrier_id_carrier` , `flight_f_date`)
    REFERENCES `mydb`.`flight` (`connexion_id_connexion` , `connexion_carrier_id_carrier` , `f_date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_customer1`
    FOREIGN KEY (`customer_id_customer`)
    REFERENCES `mydb`.`customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
