-- MySQL Script generated by MySQL Workbench
-- Fri Feb 14 12:58:02 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema escuela
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escuela
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escuela` DEFAULT CHARACTER SET utf8 ;
USE `escuela` ;

-- -----------------------------------------------------
-- Table `escuela`.`asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`asignatura` (
  `id_asignatura` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `curso` VARCHAR(45) NULL,
  `horas_semana` DECIMAL(2,2) NULL,
  PRIMARY KEY (`id_asignatura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`alumno` (
  `id_alumno` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  PRIMARY KEY (`id_alumno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`departamento` (
  `id_departamento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `id_directorr` INT NOT NULL,
  PRIMARY KEY (`id_departamento`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_departamento_profesor1_idx` (`id_directorr` ASC) VISIBLE,
  CONSTRAINT `fk_departamento_profesor1`
    FOREIGN KEY (`id_directorr`)
    REFERENCES `escuela`.`profesor` (`id_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`profesor` (
  `id_profesor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `departamento_id_departamento` INT NOT NULL,
  PRIMARY KEY (`id_profesor`, `departamento_id_departamento`),
  INDEX `fk_profesor_departamento1_idx` (`departamento_id_departamento` ASC) VISIBLE,
  CONSTRAINT `fk_profesor_departamento1`
    FOREIGN KEY (`departamento_id_departamento`)
    REFERENCES `escuela`.`departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`grupo` (
  `id_grupo` INT NOT NULL AUTO_INCREMENT,
  `curso` VARCHAR(45) NOT NULL,
  `letra` VARCHAR(45) NULL,
  `asignatura_id_asignatura` INT NOT NULL,
  PRIMARY KEY (`id_grupo`, `asignatura_id_asignatura`),
  INDEX `fk_grupo_asignatura1_idx` (`asignatura_id_asignatura` ASC) VISIBLE,
  CONSTRAINT `fk_grupo_asignatura1`
    FOREIGN KEY (`asignatura_id_asignatura`)
    REFERENCES `escuela`.`asignatura` (`id_asignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`aula` (
  `id_aula` INT NOT NULL AUTO_INCREMENT,
  `capacidad` INT NOT NULL,
  `ubicacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_aula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`grupo_alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`grupo_alumno` (
  `grupo_id_grupo` INT NOT NULL,
  `alumno_id_alumno` INT NOT NULL,
  `fecha_matriculacion` DATE NOT NULL,
  `calificación` DECIMAL(2,2) NULL,
  PRIMARY KEY (`grupo_id_grupo`, `alumno_id_alumno`),
  INDEX `fk_grupo_has_alumno_alumno1_idx` (`alumno_id_alumno` ASC) VISIBLE,
  INDEX `fk_grupo_has_alumno_grupo_idx` (`grupo_id_grupo` ASC) VISIBLE,
  CONSTRAINT `fk_grupo_has_alumno_grupo`
    FOREIGN KEY (`grupo_id_grupo`)
    REFERENCES `escuela`.`grupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_has_alumno_alumno1`
    FOREIGN KEY (`alumno_id_alumno`)
    REFERENCES `escuela`.`alumno` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`profesor_has_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`profesor_has_grupo` (
  `profesor_id_profesor` INT NOT NULL,
  `grupo_id_grupo` INT NOT NULL,
  PRIMARY KEY (`profesor_id_profesor`, `grupo_id_grupo`),
  INDEX `fk_profesor_has_grupo_grupo1_idx` (`grupo_id_grupo` ASC) VISIBLE,
  INDEX `fk_profesor_has_grupo_profesor1_idx` (`profesor_id_profesor` ASC) VISIBLE,
  CONSTRAINT `fk_profesor_has_grupo_profesor1`
    FOREIGN KEY (`profesor_id_profesor`)
    REFERENCES `escuela`.`profesor` (`id_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profesor_has_grupo_grupo1`
    FOREIGN KEY (`grupo_id_grupo`)
    REFERENCES `escuela`.`grupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`grupo_has_aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`grupo_has_aula` (
  `grupo_id_grupo` INT NOT NULL,
  `aula_id_aula` INT NOT NULL,
  PRIMARY KEY (`grupo_id_grupo`, `aula_id_aula`),
  INDEX `fk_grupo_has_aula_aula1_idx` (`aula_id_aula` ASC) VISIBLE,
  INDEX `fk_grupo_has_aula_grupo1_idx` (`grupo_id_grupo` ASC) VISIBLE,
  CONSTRAINT `fk_grupo_has_aula_grupo1`
    FOREIGN KEY (`grupo_id_grupo`)
    REFERENCES `escuela`.`grupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_has_aula_aula1`
    FOREIGN KEY (`aula_id_aula`)
    REFERENCES `escuela`.`aula` (`id_aula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;